informe:

	pdflatex -output-directory=tmp informe.tex
	pdflatex -output-directory=tmp informe.tex
	pdflatex -output-directory=tmp informe.tex
	cp tmp/informe.pdf ./

clean:
	@echo Cleaning trash files
	rm tmp/*